import 'package:flutter/material.dart';

final ThemeData lightColorTheme = ThemeData(
    appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF2B5EA7), foregroundColor: Color(0xFFFFFFFF)),
    colorScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF2B5EA7),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFD7E3FF),
      onPrimaryContainer: Color(0xFF001B3E),
      secondary: Color(0xFF5355A9),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFE1E0FF),
      onSecondaryContainer: Color(0xFF0A0664),
      tertiary: Color(0xFF006879),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFA9EDFF),
      onTertiaryContainer: Color(0xFF001F26),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFF3FEFF),
      onBackground: Color(0xFF002022),
      surface: Color(0xFFF3FEFF),
      onSurface: Color(0xFF002022),
      surfaceVariant: Color(0xFFE0E2EC),
      onSurfaceVariant: Color(0xFF44474E),
      outline: Color(0xFF74777F),
      onInverseSurface: Color(0xFFC3FBFF),
      inverseSurface: Color(0xFF00373A),
      inversePrimary: Color(0xFFAAC7FF),
      shadow: Color(0xFF000000),
      surfaceTint: Color(0xFF2B5EA7),
      outlineVariant: Color(0xFFC4C6D0),
      scrim: Color(0xFF000000),
    ));

final ThemeData darkColorTheme = ThemeData(
    appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFFAAC7FF), foregroundColor: Color(0xFF002F65)),
    colorScheme: const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFAAC7FF),
      onPrimary: Color(0xFF002F65),
      primaryContainer: Color(0xFF01458E),
      onPrimaryContainer: Color(0xFFD7E3FF),
      secondary: Color(0xFFC0C1FF),
      onSecondary: Color(0xFF232478),
      secondaryContainer: Color(0xFF3B3D8F),
      onSecondaryContainer: Color(0xFFE1E0FF),
      tertiary: Color(0xFF54D7F2),
      onTertiary: Color(0xFF003640),
      tertiaryContainer: Color(0xFF004E5B),
      onTertiaryContainer: Color(0xFFA9EDFF),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF002022),
      onBackground: Color(0xFF70F5FF),
      surface: Color(0xFF002022),
      onSurface: Color(0xFF70F5FF),
      surfaceVariant: Color(0xFF44474E),
      onSurfaceVariant: Color(0xFFC4C6D0),
      outline: Color(0xFF8E9099),
      onInverseSurface: Color(0xFF002022),
      inverseSurface: Color(0xFF70F5FF),
      inversePrimary: Color(0xFF2B5EA7),
      shadow: Color(0xFF000000),
      surfaceTint: Color(0xFFAAC7FF),
      outlineVariant: Color(0xFF44474E),
      scrim: Color(0xFF000000),
    ));
