import 'package:flutter/material.dart';

final ThemeData lightColorTheme = ThemeData(
    appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF9C4147), foregroundColor: Color(0xFFFFFFFF)),
    colorScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF9C4147),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFDADA),
      onPrimaryContainer: Color(0xFF40000B),
      secondary: Color(0xFF9C4146),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFFDAD9),
      onSecondaryContainer: Color(0xFF40000A),
      tertiary: Color(0xFF9C4146),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFDAD9),
      onTertiaryContainer: Color(0xFF40000A),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF40000E),
      surfaceContainerHighest: Color(0xFFF4DDDD),
      onSurfaceVariant: Color(0xFF524343),
      outline: Color(0xFF857373),
      onInverseSurface: Color(0xFFFFECED),
      inverseSurface: Color(0xFF5F1220),
      inversePrimary: Color(0xFFFFB3B4),
      shadow: Color(0xFF000000),
      surfaceTint: Color(0xFF9C4147),
      outlineVariant: Color(0xFFD7C1C1),
      scrim: Color(0xFF000000),
    ));

final ThemeData darkColorTheme = ThemeData(
    appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFFFFB3B4), foregroundColor: Color(0xFF5F121C)),
    colorScheme: const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFB3B4),
      onPrimary: Color(0xFF5F121C),
      primaryContainer: Color(0xFF7E2931),
      onPrimaryContainer: Color(0xFFFFDADA),
      secondary: Color(0xFFFFB3B4),
      onSecondary: Color(0xFF5F131C),
      secondaryContainer: Color(0xFF7E2A30),
      onSecondaryContainer: Color(0xFFFFDAD9),
      tertiary: Color(0xFFFFB3B4),
      onTertiary: Color(0xFF5F131C),
      tertiaryContainer: Color(0xFF7E2A30),
      onTertiaryContainer: Color(0xFFFFDAD9),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      surface: Color(0xFF40000E),
      onSurface: Color(0xFFFFDADB),
      surfaceContainerHighest: Color(0xFF524343),
      onSurfaceVariant: Color(0xFFD7C1C1),
      outline: Color(0xFF9F8C8C),
      onInverseSurface: Color(0xFF40000E),
      inverseSurface: Color(0xFFFFDADB),
      inversePrimary: Color(0xFF9C4147),
      shadow: Color(0xFF000000),
      surfaceTint: Color(0xFFFFB3B4),
      outlineVariant: Color(0xFF524343),
      scrim: Color(0xFF000000),
    ));
