import 'package:flutter/material.dart';

final ThemeData lightColorTheme = ThemeData(
    appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF246C2D), foregroundColor: Color(0xFFFFFFFF)),
    colorScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF246C2D),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFA8F5A5),
      onPrimaryContainer: Color(0xFF002105),
      secondary: Color(0xFF7E5700),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFFDEAB),
      onSecondaryContainer: Color(0xFF271900),
      tertiary: Color(0xFF765B00),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFDF95),
      onTertiaryContainer: Color(0xFF251A00),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFFFBFF),
      onBackground: Color(0xFF3F0018),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF3F0018),
      surfaceVariant: Color(0xFFDEE5D9),
      onSurfaceVariant: Color(0xFF424940),
      outline: Color(0xFF72796F),
      onInverseSurface: Color(0xFFFFECEE),
      inverseSurface: Color(0xFF5F112C),
      inversePrimary: Color(0xFF8DD88B),
      shadow: Color(0xFF000000),
      surfaceTint: Color(0xFF246C2D),
      outlineVariant: Color(0xFFC2C9BD),
      scrim: Color(0xFF000000),
    ));

final ThemeData darkColorTheme = ThemeData(
    appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF8DD88B), foregroundColor: Color(0xFF00390D)),
    colorScheme: const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF8DD88B),
      onPrimary: Color(0xFF00390D),
      primaryContainer: Color(0xFF005317),
      onPrimaryContainer: Color(0xFFA8F5A5),
      secondary: Color(0xFFFABC49),
      onSecondary: Color(0xFF422C00),
      secondaryContainer: Color(0xFF5F4100),
      onSecondaryContainer: Color(0xFFFFDEAB),
      tertiary: Color(0xFFEEC148),
      onTertiary: Color(0xFF3E2E00),
      tertiaryContainer: Color(0xFF594400),
      onTertiaryContainer: Color(0xFFFFDF95),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF3F0018),
      onBackground: Color(0xFFFFD9E0),
      surface: Color(0xFF3F0018),
      onSurface: Color(0xFFFFD9E0),
      surfaceVariant: Color(0xFF424940),
      onSurfaceVariant: Color(0xFFC2C9BD),
      outline: Color(0xFF8C9388),
      onInverseSurface: Color(0xFF3F0018),
      inverseSurface: Color(0xFFFFD9E0),
      inversePrimary: Color(0xFF246C2D),
      shadow: Color(0xFF000000),
      surfaceTint: Color(0xFF8DD88B),
      outlineVariant: Color(0xFF424940),
      scrim: Color(0xFF000000),
    ));
