import 'package:flutter/material.dart';

final ThemeData lightColorTheme = ThemeData(
    appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF755B00), foregroundColor: Color(0xFFFFFFFF)),
    colorScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF755B00),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFDF91),
      onPrimaryContainer: Color(0xFF241A00),
      secondary: Color(0xFF7E5700),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFFDEAD),
      onSecondaryContainer: Color(0xFF281900),
      tertiary: Color(0xFF855400),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFDDB7),
      onTertiaryContainer: Color(0xFF2A1700),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF2C1700),
      surfaceContainerHighest: Color(0xFFECE1CF),
      onSurfaceVariant: Color(0xFF4C4639),
      outline: Color(0xFF7E7667),
      onInverseSurface: Color(0xFFFFEEE0),
      inverseSurface: Color(0xFF482900),
      inversePrimary: Color(0xFFECC148),
      shadow: Color(0xFF000000),
      surfaceTint: Color(0xFF755B00),
      outlineVariant: Color(0xFFCFC5B4),
      scrim: Color(0xFF000000),
    ));

final ThemeData darkColorTheme = ThemeData(
    appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFFECC148), foregroundColor: Color(0xFF3D2E00)),
    colorScheme: const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFECC148),
      onPrimary: Color(0xFF3D2E00),
      primaryContainer: Color(0xFF594400),
      onPrimaryContainer: Color(0xFFFFDF91),
      secondary: Color(0xFFFBBB4A),
      onSecondary: Color(0xFF432C00),
      secondaryContainer: Color(0xFF604100),
      onSecondaryContainer: Color(0xFFFFDEAD),
      tertiary: Color(0xFFFFB95D),
      onTertiary: Color(0xFF462A00),
      tertiaryContainer: Color(0xFF653E00),
      onTertiaryContainer: Color(0xFFFFDDB7),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      surface: Color(0xFF2C1700),
      onSurface: Color(0xFFFFDCBB),
      surfaceContainerHighest: Color(0xFF4C4639),
      onSurfaceVariant: Color(0xFFCFC5B4),
      outline: Color(0xFF989080),
      onInverseSurface: Color(0xFF2C1700),
      inverseSurface: Color(0xFFFFDCBB),
      inversePrimary: Color(0xFF755B00),
      shadow: Color(0xFF000000),
      surfaceTint: Color(0xFFECC148),
      outlineVariant: Color(0xFF4C4639),
      scrim: Color(0xFF000000),
    ));
